stages:
  - build
  - test

variables:
  GO111MODULE: "on"

build:
  stage: build
  script:
    - go build
  tags:
    - golang

test:
  stage: test
  script:
    - go test -v ./...
  tags:
    - golang

coverage:
  stage: test
  script:
    - go install
    - go test ./... -coverprofile=coverage.txt -covermode count
    - go get github.com/boumenot/gocover-cobertura
    - go run github.com/boumenot/gocover-cobertura < coverage.txt > coverage.xml
  coverage: /^coverage:\s(\d+(?:\.\d+)?%)/
  artifacts:
    name: $CI_JOB_NAME/coverage.txt
    paths:
      - coverage.xml
    expire_in: 2 days
    reports:
      cobertura: coverage.xml
  tags:
    - golang
