stages:
  - build
  - test

variables:
  GO111MODULE: "on"

build:
  stage: build
  script:
    - go build
  tags:
    - golang

test:
  stage: test
  script:
    - go test -v ./...
  tags:
    - golang

coverage:
  stage: test
  script:
    - go get github.com/kjellkvinge/gocover
    - go run github.com/kjellkvinge/gocover
  coverage: /^\s*Total covered: \d+\.\d+%/
  tags:
    - golang
