stages:
  - build
  - test

variables:
  GO111MODULE: "on"

build:
  stage: build
  script:
    - go build
  tags:
    - golang

test:
  stage: test
  script:
    - go test -v ./...
  tags:
    - golang

coverage:
  stage: test
  script:
    - go test ./... -coverprofile=coverage.txt -covermode=count
    - go install github.com/boumenot/gocover-cobertura@latest
    - gocover-cobertura -input=coverage.txt -output=coverage.xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        cobertura: coverage.xml
  tags:
    - golang
