stages:
  - build
  - test

variables:
  GO111MODULE: "on"

build:
  stage: build
  script:
    - go build
  tags:
    - golang

test:
  stage: test
  script:
    - go test -v ./...
  tags:
    - golang

coverage:
  stage: test
  script:
    - go install
    - go test ./... -coverprofile=coverage.txt -covermode count
    - go get github.com/boumenot/gocover-cobertura
    - go run github.com/boumenot/gocover-cobertura < coverage.txt > coverage.xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  tags:
    - golang
